import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './component/Footer/Footer';
import Navbar from './component/Navbar/Navbar';
import SliderDevelop from './component/SliderDevelop/SliderDevelop';
import DevMedia from './component/Devmedia/DevMedia';
 
 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Marakez',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>
        {children}
        <Footer/>
        {/* <DevMedia/> */}
        
      {/* <SliderDevelop/> */}

       
        </body>
    </html>
  )
}
